#!/bin/bash

CONFIG="$HOME/.config/hypr/waybar/config"
STYLE="$HOME/.config/hypr/waybar/style.css"

startup() {
	if [[ ! $(pidof waybar) ]]; then
		waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
	fi
}

reload() {
	if [[ $(pidof waybar) ]]; then
		pkill waybar
	fi
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
}

if [[ "$1" == "--reload" ]]; then
	reload
else
	startup
fi
